{"uuid": "e10a5e39-a7f0-4716-be56-cdca584d489f", "children": ["9396b27f-1bf5-44dc-8cec-4217329f8813"], "befores": [{"name": "login", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_RESET\n  (Session info: chrome=137.0.7151.69)\nStacktrace:\n\tGetHandleVerifier [0x0x7ff70ee1fea5+79173]\n\tGetHandleVerifier [0x0x7ff70ee1ff00+79264]\n\t(No symbol) [0x0x7ff70ebd9e5a]\n\t(No symbol) [0x0x7ff70ebd6874]\n\t(No symbol) [0x0x7ff70ebc7589]\n\t(No symbol) [0x0x7ff70ebc9331]\n\t(No symbol) [0x0x7ff70ebc78a6]\n\t(No symbol) [0x0x7ff70ebc7306]\n\t(No symbol) [0x0x7ff70ebc6fca]\n\t(No symbol) [0x0x7ff70ebc4b9f]\n\t(No symbol) [0x0x7ff70ebc541c]\n\t(No symbol) [0x0x7ff70ebdde0a]\n\t(No symbol) [0x0x7ff70ec81dfe]\n\t(No symbol) [0x0x7ff70ec5896a]\n\t(No symbol) [0x0x7ff70ec8100d]\n\t(No symbol) [0x0x7ff70ec58743]\n\t(No symbol) [0x0x7ff70ec214c1]\n\t(No symbol) [0x0x7ff70ec22253]\n\tGetHandleVerifier [0x0x7ff70f0ea2dd+3004797]\n\tGetHandleVerifier [0x0x7ff70f0e472d+2981325]\n\tGetHandleVerifier [0x0x7ff70f103380+3107360]\n\tGetHandleVerifier [0x0x7ff70ee3aa2e+188622]\n\tGetHandleVerifier [0x0x7ff70ee422bf+219487]\n\tGetHandleVerifier [0x0x7ff70ee28df4+115860]\n\tGetHandleVerifier [0x0x7ff70ee28fa9+116297]\n\tGetHandleVerifier [0x0x7ff70ee0f558+11256]\n\tBaseThreadInitThunk [0x0x7ffda8bf7374+20]\n\tRtlUserThreadStart [0x0x7ffdaa1fcc91+33]\n\n", "trace": "  File \"C:\\Users\\Administrator\\Desktop\\test\\venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 38, in run_old_style_hookwrapper\n    res = yield\n          ^^^^^\n  File \"C:\\Users\\Administrator\\Desktop\\test\\venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 139, in _multicall\n    teardown.throw(exception)\n    ~~~~~~~~~~~~~~^^^^^^^^^^^\n  File \"C:\\Users\\Administrator\\Desktop\\test\\venv\\Lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"C:\\Users\\Administrator\\Desktop\\test\\venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 121, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\Administrator\\Desktop\\test\\venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1195, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\Administrator\\Desktop\\test\\venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 929, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"C:\\Users\\Administrator\\Desktop\\test\\test_审批流程.py\", line 33, in login\n    browser.get(\"https://192.168.2.42:9529\")\n    ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Administrator\\Desktop\\test\\venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 472, in get\n    self.execute(Command.GET, {\"url\": url})\n    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Administrator\\Desktop\\test\\venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 447, in execute\n    self.error_handler.check_response(response)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^\n  File \"C:\\Users\\Administrator\\Desktop\\test\\venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 232, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1751618718383, "stop": 1751618718616}], "start": 1751618718383, "stop": 1751618720093}