{"uuid": "17389251-27c3-4163-a905-d34bcac4cf91", "children": ["c812bcd9-0655-4143-87cf-5c6cd5bacfc4", "320da9e7-a9dc-451c-823b-48d03293816d"], "befores": [{"name": "login", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.InvalidSessionIdException: Message: invalid session id\nStacktrace:\n\tGetHandleVerifier [0x0x7ff764d7fea5+79173]\n\tGetHandleVerifier [0x0x7ff764d7ff00+79264]\n\t(No symbol) [0x0x7ff764b39c8c]\n\t(No symbol) [0x0x7ff764b805ef]\n\t(No symbol) [0x0x7ff764bb8832]\n\t(No symbol) [0x0x7ff764bb3233]\n\t(No symbol) [0x0x7ff764bb22f9]\n\t(No symbol) [0x0x7ff764b05fc5]\n\tGetHandleVerifier [0x0x7ff76504a2dd+3004797]\n\tGetHandleVerifier [0x0x7ff76504472d+2981325]\n\tGetHandleVerifier [0x0x7ff765063380+3107360]\n\tGetHandleVerifier [0x0x7ff764d9aa2e+188622]\n\tGetHandleVerifier [0x0x7ff764da22bf+219487]\n\t(No symbol) [0x0x7ff764b05036]\n\tGetHandleVerifier [0x0x7ff765163c78+4158232]\n\tBaseThreadInitThunk [0x0x7ffda8bf7374+20]\n\tRtlUserThreadStart [0x0x7ffdaa1fcc91+33]\n\n", "trace": "  File \"C:\\Users\\Administrator\\Desktop\\test\\venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 38, in run_old_style_hookwrapper\n    res = yield\n          ^^^^^\n  File \"C:\\Users\\Administrator\\Desktop\\test\\venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 139, in _multicall\n    teardown.throw(exception)\n    ~~~~~~~~~~~~~~^^^^^^^^^^^\n  File \"C:\\Users\\Administrator\\Desktop\\test\\venv\\Lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"C:\\Users\\Administrator\\Desktop\\test\\venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 121, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\Administrator\\Desktop\\test\\venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1195, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\Administrator\\Desktop\\test\\venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 929, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"C:\\Users\\Administrator\\Desktop\\test\\test_新增简历.py\", line 126, in login\n    allure.attach(driver.get_screenshot_as_png(), name=\"登录失败截图\", attachment_type=allure.attachment_type.PNG)\n                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^\n  File \"C:\\Users\\Administrator\\Desktop\\test\\venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 1019, in get_screenshot_as_png\n    return b64decode(self.get_screenshot_as_base64().encode(\"ascii\"))\n                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^\n  File \"C:\\Users\\Administrator\\Desktop\\test\\venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 1029, in get_screenshot_as_base64\n    return self.execute(Command.SCREENSHOT)[\"value\"]\n           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Administrator\\Desktop\\test\\venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 447, in execute\n    self.error_handler.check_response(response)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^\n  File \"C:\\Users\\Administrator\\Desktop\\test\\venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 232, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1752199805464, "stop": 1752199808854}], "start": 1752199805464, "stop": 1752199812127}