{"uuid": "122509d0-6e78-4f2c-8807-09ed6ccba765", "children": ["07de3fd3-603e-4845-b705-4eb164588f08"], "befores": [{"name": "cleanup", "status": "passed", "start": 1753511055974, "stop": 1753511055974}], "afters": [{"name": "cleanup::0", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: <unknown>: Failed to read the 'localStorage' property from 'Window': Storage is disabled inside 'data:' URLs.\n  (Session info: MicrosoftEdge=136.0.3240.64)\nStacktrace:\n\tGetHandleVerifier [0x00007FF65360F935+25029]\n\t(No symbol) [0x00007FF653564940]\n\tMicrosoft::Applications::Events::EventProperty::to_string [0x00007FF65386AA3A+1947706]\n\t(No symbol) [0x00007FF65333230C]\n\t(No symbol) [0x00007FF653334EE1]\n\t(No symbol) [0x00007FF6533B71F3]\n\t(No symbol) [0x00007FF65339908A]\n\t(No symbol) [0x00007FF65336E15D]\n\t(No symbol) [0x00007FF6533B6698]\n\t(No symbol) [0x00007FF653398DF3]\n\t(No symbol) [0x00007FF65336D6A6]\n\t(No symbol) [0x00007FF65336CBB3]\n\t(No symbol) [0x00007FF65336D4D3]\n\t(No symbol) [0x00007FF653475F0D]\n\t(No symbol) [0x00007FF653483AAF]\n\t(No symbol) [0x00007FF65347C49F]\n\tMicrosoft::Applications::Events::EventProperty::to_string [0x00007FF6536D49EA+284650]\n\t(No symbol) [0x00007FF6535722D1]\n\t(No symbol) [0x00007FF65356AD74]\n\t(No symbol) [0x00007FF65356AEC3]\n\t(No symbol) [0x00007FF65355CB06]\n\tBaseThreadInitThunk [0x00007FFAB4797374+20]\n\tRtlUserThreadStart [0x00007FFAB63DCC91+33]\n\n", "trace": "  File \"D:\\t\\.venv\\Lib\\site-packages\\allure_commons\\_allure.py\", line 221, in __call__\n    return self._fixture_function(*args, **kwargs)\n           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^\n  File \"D:\\t\\.venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 938, in _teardown_yield_fixture\n    next(it)\n    ~~~~^^^^\n  File \"D:\\test\\conftest.py\", line 9, in cleanup\n    driver.execute_script(\"window.localStorage.clear();\")\n    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\t\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 551, in execute_script\n    return self.execute(command, {\"script\": script, \"args\": converted_args})[\"value\"]\n           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\t\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 454, in execute\n    self.error_handler.check_response(response)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^\n  File \"D:\\t\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 232, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1753511055976, "stop": 1753511056004}], "start": 1753511055974, "stop": 1753511056004}