{"uuid": "ab03acc0-358a-463d-91ed-d8bf96482443", "children": ["dcba6994-224c-4544-82fa-f7f06f6c17e4", "3cf1802b-43cb-4924-80f2-4b8f578b9995", "d7cf0314-9221-4359-a616-adef091fb4ef", "d0e644dd-53b6-462b-8f56-57f4e2f36e6a", "dd1836f4-391a-437b-ac52-965415c57960"], "befores": [{"name": "login", "status": "broken", "statusDetails": {"message": "IndexError: list index out of range\n", "trace": "  File \"D:\\t\\.venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 38, in run_old_style_hookwrapper\n    res = yield\n          ^^^^^\n  File \"D:\\t\\.venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 139, in _multicall\n    teardown.throw(exception)\n    ~~~~~~~~~~~~~~^^^^^^^^^^^\n  File \"D:\\t\\.venv\\Lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"D:\\t\\.venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 121, in _multicall\n    res = hook_impl.function(*args)\n  File \"D:\\t\\.venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1195, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"D:\\t\\.venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 929, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"C:\\Users\\Administrator\\Desktop\\test\\系统设置\\系统管理设置\\菜单权限管理\\test_资源管理.py\", line 134, in login\n    raise e\n  File \"C:\\Users\\Administrator\\Desktop\\test\\系统设置\\系统管理设置\\菜单权限管理\\test_资源管理.py\", line 107, in login\n    captcha_data = captcha_img.get_attribute(\"src\").split(\",\")[1]\n                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^\n"}, "attachments": [{"name": "登录失败截图", "source": "4ea94f60-6e4f-4b47-b134-199e6b5f1de8-attachment.png", "type": "image/png"}], "start": 1753514174009, "stop": 1753514176253}], "start": 1753514174009, "stop": 1753514176598}